storage: ../tmp/local-registry/storage

uplinks:
  npmjs:
    url: https://registry.npmjs.org/
    cache: true
  yarn:
    url: https://registry.yarnpkg.com
    cache: true

packages:
  '@*/*':
    # scoped packages
    access: $all
    publish: $all
    unpublish: $all
    proxy: npmjs

  '**':
    access: $all
    publish: $all
    unpublish: $all
    proxy: npmjs

logs:
  type: stdout
  format: pretty
  level: http

web:
  enabled: true
  title: Stacks Nx Registry
