storage: ../tmp/local-registry/storage

uplinks:
  npmjs:
    url: https://registry.npmjs.org/
    cache: true
    maxage: 60m
  yarn:
    url: https://registry.yarnpkg.com
    cache: true
    maxage: 60m

packages:
  '**':
    access: $all
    publish: $all
    unpublish: $all
    proxy: npmjs

publish:
  allow_offline: true

web:
  enabled: true
  title: Stacks Nx Registry
