####### DNS & Public IP Variables
variable "app_gateway_frontend_ip_name" {
  description = "The name of the frontend IP configuration for the application gateway."
  type        = string
}

variable "app_gateway_frontend_ip_rg" {
  description = "The resource group of the application gateway frontend IP."
  type        = string
}

variable "dns_a_record_name" {
  description = "The name of the DNS A record."
  type        = string
}

variable "dns_a_record_ttl" {
  description = "The TTL (Time To Live) of the DNS A record in seconds."
  type        = number
  default     = 300
}

variable "dns_zone" {
  description = "The DNS zone in which to create the A record."
  type        = string
}

variable "dns_zone_rg" {
  description = "The resource group of the DNS zone."
  type        = string
}

###### Label Variables
variable "location_name_map" {
  description = "A map of Azure region names to custom short names."
  type        = map(string)

  default = {
    northeurope   = "eun"
    westeurope    = "euw"
    uksouth       = "uks"
    ukwest        = "ukw"
    eastus        = "use"
    eastus2       = "use2"
    westus        = "usw"
    eastasia      = "ase"
    southeastasia = "asse"
  }
}

variable "name_company" {
  description = "The name of the company"
  type        = string
}

variable "name_environment" {
  description = "The environment name"
  type        = string
}

variable "name_project" {
  description = "The project stack name"
  type        = string
}

variable "name_domain" {
  description = "The domain name."
  type        = string
}


###### Redis Variables
variable "create_redis" {
  description = "Flag to create a Redis instance."
  type        = bool
  default     = null
}

variable "custom_name" {
  description = "Provide a custom UNIQUE name for your cache instance. This overrides the name that is generated by the Claranet Redis module."
  type        = string
  default     = null
}

variable "attributes" {
  description = "Additional attributes for the resources."
  type        = list(string)
  default     = []
}

# Required By Module IF You wish to create Redis Cache Instance ONLY!
variable "redis_resource_group_name" {
  description = "The name of the resource group to deploy Redis to."
  type        = string
  default     = null
}

variable "location" {
  description = "The region that your resources will deploy to."
  type        = string
}

variable "logs_destinations_ids" {
  description = "The list of destination IDs for logging."
  type        = list(string)
  default     = []
}

variable "sku_name" {
  description = "The SKU name for the Redis instance."
  type        = string
  default     = "Basic"
}

variable "capacity" {
  description = "Redis size: (Basic/Standard: 1,2,3,4,5,6) (Premium: 1,2,3,4)"
  type        = number
  default     = 1
}

variable "public_network_access_enabled" {
  description = "Flag to enable public network access"
  type        = bool
  default     = true
}

variable "allow_non_ssl_connections" {
  description = "Flag to allow non-SSL connections"
  type        = bool
  default     = true
}

# OPTIONAL!! Redis Additional Configuration Variables (Some of these cannot be set based on SKU Family Chosen)
variable "aof_backup_enabled" {
  description = "Flag to enable AOF backup"
  type        = bool
  default     = null
}

variable "aof_storage_connection_string_0" {
  description = "Connection string for the first AOF storage"
  type        = string
  default     = null
}

variable "aof_storage_connection_string_1" {
  description = "Connection string for the second AOF storage"
  type        = string
  default     = null
}

variable "enable_authentication" {
  description = "Flag to enable authentication"
  type        = bool
  default     = null
}

variable "active_directory_authentication_enabled" {
  description = "Flag to enable Active Directory authentication"
  type        = bool
  default     = null
}

variable "maxmemory_reserved" {
  description = "Amount of memory reserved"
  type        = number
  default     = null
}

variable "maxmemory_delta" {
  description = "Amount of memory delta"
  type        = number
  default     = null
}

variable "maxmemory_policy" {
  description = "Memory eviction policy"
  type        = string
  default     = null
}

variable "maxfragmentationmemory_reserved" {
  description = "Amount of fragmentation memory reserved"
  type        = number
  default     = null
}

variable "rdb_backup_enabled" {
  description = "Flag to enable RDB backup"
  type        = bool
  default     = null
}

variable "rdb_backup_frequency" {
  description = "Frequency of RDB backups"
  type        = number
  default     = null
}

variable "rdb_backup_max_snapshot_count" {
  description = "Maximum number of RDB snapshots to keep"
  type        = number
  default     = null
}

variable "rdb_storage_connection_string" {
  description = "Connection string for RDB storage"
  type        = string
  default     = null
}

variable "notify_keyspace_events" {
  description = "Keyspace events to notify"
  type        = string
  default     = null
}
