export const CYPRESS_VERSION = '^12.12.0';
export const NRWLCYPRESS_VERSION = '15.9.4';
export const CYPRESSMULTIREPORTERS_VERSION = '^1.6.3';
export const MOCHAWESOME_VERSION = '^7.1.3';
export const MOCHAWESOMEMERGE_VERSION = '^4.3.0';
export const MOCHAWESOMEJUNITREPORTER_VERSION = '2.2.0';
