export const AXE_CORE_PLAYWRIGHT_VERSION = '4.9.0';
export const AXE_RESULTS_PRETTY_PRINT_VERSION = '1.0.2';
export const APPLITOOLS_EYES_PLAYWRIGHT_VERSION = '1.27.2';
export const PLAYWRIGHT_VERSION = '^1.44.0';
