name: Release

description: Release packages

runs:
  using: composite
  steps:
    - name: Check Authentication with Registry
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      shell: bash
      run: npm whoami

    - name: Release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        NX_CLOUD_ACCESS_TOKEN: ${{ secrets.NX_CLOUD_ACCESS_TOKEN }}
      shell: bash
      run: npx nx affected --base=last-release --target=release

    - name: Tag last-release
      shell: bash
      run: git tag -f last-release

    - name: Push changes
      uses: ad-m/github-push-action@552c074ed701137ebd2bf098e70c394ca293e87f
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: ${{ github.ref }}
        force: true
        tags: true
