export const PACKAGE_JSON = 'package.json';
export const HUSKY_VERSION = '^9.0.11';
export const COMMITLINT_CLI_VERSION = '19.3.0';
export const COMMITLINT_CONFIG_CONVENTIONAL_VERSION = '19.2.2';
export const COMMITLINT_CONFIG_NX_SCOPES_VERSION = '19.3.1';
export const COMMITLINT_CZ_COMMITLINT_VERSION = '19.2.0';
export const COMMITIZEN_VERSION = '^4.3.0';
export const ESLINT_VERSION = '8.57.0';
export const ESLINT_CONFIG_AIRBNB_VERSION = '19.0.4';
export const ESLINT_CONFIG_PRETTIER_VERSION = '9.0.0';
export const ESLINT_IMPORT_RESOLVER_TS_VERSION = '3.5.5';
export const ESLINT_PLUGIN_VERSION = '7.3.0';
export const ESLINT_PLUGIN_COMPAT_VERSION = '4.1.4';
export const ESLINT_PLUGIN_IMPORT_VERSION = '2.27.0';
export const ESLINT_PLUGIN_PRETTIER_VERSION = '4.2.1';
export const ESLINT_PLUGIN_SECURITY_VERSION = '1.4.0';
export const ESLINT_PLUGIN_UNICORN_VERSION = '53.0.0';
export const ESLINT_PLUGIN_JEST = '28.5.0';
export const ESLINT_PLUGIN_JEST_DOM = '5.1.0';
export const ESLINT_PLUGIN_NO_UNSANITIZED = '4.0.2';

export const LINT_STAGED_VERSION = '13.1.2';

export const NODE_LTS = '22.2.0';
