export const WINSTON_VERSION = '3.13.0';
export const ESLINT_PLUGIN_TESTING_LIBRARY_VERSION = '6.2.2';
export const TYPESCRIPT_ESLINT_PLUGIN_VERSION = '7.18.0';
export const TYPESCRIPT_ESLINT_PARSER_VERSION = '7.18.0';
