export const ESLINT_PLUGIN_TESTING_LIBRARY_VERSION = '^7.0.0';
export const NEXT_ESLINT_PLUGIN_VERSION = '^15.1.6';
export const EXPRESS_VERSION = '4.19.2';
export const TYPES_EXPRESS_VERSION = '4.17.21';
