export const ESLINT_PLUGIN_TESTING_LIBRARY_VERSION = '6.2.2';
export const TYPESCRIPT_ESLINT_PLUGIN_VERSION = '7.18.0';
export const TYPESCRIPT_ESLINT_PARSER_VERSION = '7.18.0';
export const EXPRESS_VERSION = '4.19.2';
export const TYPES_EXPRESS_VERSION = '4.17.21';
