# Production values for <%= projectName %>.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
fullnameOverride: <%= projectName %>

image:
    repository: <%= prodRegistryPath %>

ingress:
    hosts:
        - host: <%= projectName %>.<%= externalDomain %>
          paths:
              - path: /
                pathType: ImplementationSpecific
    tls:
        - hosts:
              - <%= externalDomain %>

podAnnotations:
    instrumentation.opentelemetry.io/inject-nodejs: '<%= openTelemetry %>'