---
id: nx-plugins_tests
title: Tests
description: To keep the resources in a known configuration, e.g. Azure Cache for Redis, up to date the project contains infrastructure tests. 
weight: 70
---

== Infrastructure Tests

Infrastructure tests have been built into the EDIR pipeline. These tests are designed to check that the deployed resources are configured as expected.

The tests are located in `deploy/tests` and are https://inspec.io[Inspec] controls. The following table shows the tests that are being performed.

.InSpec Controls
[cols="1,3a",options="header",stripes=even]
|===
| Details| Description
| Name: `azure-resource-group`

Filename: `controls/resource_group.rb` | The resource group that everything is deployed to, the control checks:

- the group exists
- it is in the correct location
- its deployment succeeded
| Name: `redis-instance-existence`

Filename: `controls/redis.rb` | Ensures the Redis instance exists within the resource group.

- it should exist
- it has the correct name
| Name: `redis-sku-and-size`

Filename: `controls/redis.rb` | Ensures the Redis instance has the correct SKU and size.

- it has the correct SKU name
- it has the correct SKU family
- it has the correct capacity
| Name: `redis-availability-status`

Filename: `controls/redis.rb` | Ensures the Redis instance is available and healthy.

- its provisioning state should be 'Succeeded'
- it should have a hostname
- it should have the correct port
- it should have the correct SSL port
| Name: `redis-configuration`

Filename: `controls/redis.rb` | Ensures the Redis instance has correct configurations.

- it has the correct maxmemory-reserved
- it has the correct maxmemory-delta
- it has the correct maxmemory-policy
|===

NOTE: There is an ADO pipeline that runs these tests on a schedule at 0600 which can be added to Azure DevOps. The file for this pipeline is `build/azDevOps/azure/infrastructure-tests.yml`.
