name: E2E
on:
  pull_request:
    branches:
    - main
    types: [opened, synchronize, reopened]
jobs:
  e2e:
    permissions:
      contents: read
    strategy:
      matrix:
        os:
        - ubuntu-latest
        - macos-latest
        include:
        - os: ubuntu-latest
          os-name: ubuntu
        - os: macos-latest
          os-name: osx
        node_version:
        - '18'
        package_manager:
        - npm
        - yarn
        - pnpm
    name: E2E ${{ matrix.os-name }}/${{ matrix.package_manager }}
    uses: nrwl/ci/.github/workflows/nx-cloud-main.yml@v0.11.0
    with:
      node-version: 18
      number-of-agents: 3
      runs-on: ${{ matrix.os }}
      init-commands: |
        git config --global user.name '@ensono'
        git config --global user.email 'git@ensono.com'
        npx nx-cloud start-ci-run --agent-count=3
      parallel-commands-on-agents: |
        npx nx affected --base=last-release --target=e2e --configuration="ci" --parallel=3
      environment-variables: |
        NX_E2E_CI_CACHE_KEY=e2e-gha-${{ matrix.os }}-18 #${{ matrix.node_version }}-${{ matrix.package_manager }}
        NODE_OPTIONS=--max_old_space_size=8192
        SELECTED_PM=${{ matrix.package_manager }}
        NX_VERBOSE_LOGGING=${{ 'true' }}
        NX_E2E_SKIP_BUILD_CLEANUP=${{ 'true' }}
        NPM_CONFIG_USERCONFIG=$RUNNER_TEMP/.npmrc
    secrets:
      NX_CLOUD_ACCESS_TOKEN: ${{ secrets.NX_CLOUD_ACCESS_TOKEN }}
  stopagents:
    name: Stop Agents ${{ matrix.os-name }}
    uses: nrwl/ci/.github/workflows/nx-cloud-main.yml@v0.11.0
    with:
      runs-on: ${{ matrix.os }}
      final-commands: |
        npx nx-cloud stop-all-agents
    strategy:
      matrix:
        os:
        - ubuntu-latest
        - macos-latest
    needs: e2e
    if: always()
  agents:
    name: Nx Cloud - Agents ${{ matrix.os }}
    strategy:
      matrix:
        os:
        - ubuntu-latest
        - macos-latest
    uses: nrwl/ci/.github/workflows/nx-cloud-agents.yml@v0.11.0
    with:
      number-of-agents: 3
      runs-on: ${{ matrix.os }}
    secrets:
      NX_CLOUD_ACCESS_TOKEN: ${{ secrets.NX_CLOUD_ACCESS_TOKEN }}
