name: E2E Matrix Temp
on:
  pull_request:
    branches:
    - main
    types: [opened, synchronize, reopened]
jobs:
  e2e:
    permissions:
      contents: read
    strategy:
      matrix:
        os:
        - ubuntu-latest
        - macos-latest
        include:
        - os: ubuntu-latest
          os-name: ubuntu
        - os: macos-latest
          os-name: osx
        node_version:
        - '18'
        package_manager:
        - npm
    name: E2E ${{ matrix.os-name }}/${{ matrix.package_manager }}
    uses: nrwl/ci/.github/workflows/nx-cloud-main.yml@v0.11.0
    with:
      node-version: 18
      number-of-agents: 1
      runs-on: ${{ matrix.os }}
      parallel-commands-on-agents: |
        npx nx e2e next-e2e --target=e2e --parallel=1
      environment-variables: |
        NX_E2E_CI_CACHE_KEY=e2e-gha-${{ matrix.os }}-${{ matrix.node_version }}-${{ matrix.package_manager }}
        NODE_OPTIONS=--max_old_space_size=8192
        SELECTED_PM=${{ matrix.package_manager }}
        NX_VERBOSE_LOGGING=${{ 'true' }}
        NX_E2E_SKIP_BUILD_CLEANUP=${{ 'false' }}
        NPM_CONFIG_USERCONFIG=$RUNNER_TEMP/.npmrc
        NX_RUN_GROUP=${{ github.run_id }}-${{ matrix.os }}-${{ matrix.node_version }}-${{ matrix.package_manager }}
    secrets:
      NX_CLOUD_ACCESS_TOKEN: ${{ secrets.NX_CLOUD_ACCESS_TOKEN }}
  agents:
    name: Nx Cloud - Agents ${{ matrix.os-name }}/${{ matrix.package_manager }}
    strategy:
      matrix:
        os:
        - ubuntu-latest
        - macos-latest
        include:
        - os: ubuntu-latest
          os-name: ubuntu
        - os: macos-latest
          os-name: osx
        node_version:
        - '18'
        package_manager:
        - npm
    uses: nrwl/ci/.github/workflows/nx-cloud-agents.yml@v0.11.0
    with:
      number-of-agents: 1
      runs-on: ${{ matrix.os }}
      environment-variables: |
        NX_RUN_GROUP=${{ github.run_id }}-${{ matrix.os }}-${{ matrix.node_version }}-${{ matrix.package_manager }}
    secrets:
      NX_CLOUD_ACCESS_TOKEN: ${{ secrets.NX_CLOUD_ACCESS_TOKEN }}