name: Matrix Nx Command
on:
  workflow_dispatch:
    inputs:
      nx-command:
        description: 'Nx Command to run'
        default: 'run-many --target=e2e'
      node-version:
        description: 'Node version to use'
        type: 'number'
        default: 22
      number-of-agents:
        description: 'Number of Agents to use'
        type: 'number'
        default: 3
jobs:
  command:
    permissions:
      contents: read
    name: Matrix Command
    uses: ./.github/workflows/main.yml
    with:
      runs-on: ubuntu-latest
      node-version: ${{ inputs.node-version }}
      number-of-agents: ${{ inputs.number-of-agents }}
      parallel-commands-on-agents: |
        npx nx ${{ inputs.nx-command }}
      environment-variables: |
        NX_E2E_CI_CACHE_KEY=e2e-gha
        NODE_OPTIONS=--max_old_space_size=8192
        NX_VERBOSE_LOGGING=${{ 'true' }}
        NX_E2E_SKIP_BUILD_CLEANUP=${{ 'true' }}
        NPM_CONFIG_USERCONFIG=$RUNNER_TEMP/.npmrc
        NX_RUN_GROUP=${{ github.run_id }}
    secrets:
      NX_CLOUD_ACCESS_TOKEN: ${{ secrets.NX_CLOUD_ACCESS_TOKEN }}
  agents:
    name: Nx Cloud - Agents
    uses: ./.github/workflows/agents.yml
    with:
      runs-on: ubuntu-latest
      node-version: ${{ inputs.node-version }}
      number-of-agents: ${{ inputs.number-of-agents }}
      environment-variables: |
        NX_RUN_GROUP=${{ github.run_id }}
    secrets:
      NX_CLOUD_ACCESS_TOKEN: ${{ secrets.NX_CLOUD_ACCESS_TOKEN }}

