name: NX_Latest_E2E
on: 
  push:
  workflow_dispatch:
jobs:
  e2e:
    permissions:
      contents: read
    name: E2E
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        node-version: [16, 18]   
    runs-on: ${{ matrix.os }}
    steps:
        - name: Checkout
          uses: actions/checkout@v3

        - name: Use Node Version ${{ matrix.node-version }}
          uses: actions/setup-node@v3
          with:
            node-version: ${{ matrix.node-version }}
      
        - name: Run E2E Tests
          run: npx nx affected --skip-nx-cache --base=last-release --target=e2e
          env:
            NX_E2E_CI_CACHE_KEY: e2e-gha
            NODE_OPTIONS: --max_old_space_size=8192
            NX_VERBOSE_LOGGING: 'true'
            NX_E2E_SKIP_BUILD_CLEANUP: true'
            NPM_CONFIG_USERCONFIG: $RUNNER_TEMP/.npmrc
            NX_RUN_GROUP: ${{ github.run_id }}
            NX_CLOUD_ACCESS_TOKEN: ${{ secrets.NX_CLOUD_ACCESS_TOKEN }}
    