name: Prerelease
on:
  push:
    branches:
      - fix/5616-versioning
jobs:
  prerelease:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
        token: ${{ secrets.BOT_TOKEN }}

    - name: Setup git user
      shell: bash
      run: |
        npm config set "//registry.npmjs.org/:_authToken=$NPM_TOKEN"
        git config --global user.name '@ensono'
        git config --global user.email 'git@ensono.com'
      env:
        NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

    - uses: volta-cli/action@v4
      with:
        node-version: "18"

    - name: Node Modules Cache
      uses: actions/cache@v3
      with:
        path: ~/.npm
        key: ${{ runner.os }}-node-18-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-18-

    - name: Install
      shell: bash
      run: npm ci

    - name: Version
      shell: bash
      run: npx nx affected --target=version --base=last-prerelease --configuration=prerelease --preid="alpha-${{ github.run_number }}" --parallel=1
      env:
        NX_CLOUD_ACCESS_TOKEN: ${{ secrets.NX_CLOUD_ACCESS_TOKEN }}
        GITHUB_TOKEN: ${{ secrets.BOT_TOKEN }}
        NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

    - name: Tag last-prerelease
      shell: bash
      run: git tag -f last-prerelease

    - name: Push changes
      uses: ad-m/github-push-action@552c074ed701137ebd2bf098e70c394ca293e87f
      with:
        github_token: ${{ secrets.BOT_TOKEN }}
        branch: ${{ github.ref }}
        force: true
        tags: true
