name: Test
on:
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  test:
    name: Test
    uses: nrwl/ci/.github/workflows/nx-cloud-main.yml@v0.14.0
    with:
      node-version: 22.1.0
      number-of-agents: 3
      init-commands: |
        git config --global user.name '@ensono'
        git config --global user.email 'git@ensono.com'
        npm install -g npm@latest
        npm cache clean --force
        # Add a command to display the npm log file if an error occurs
        npm ci || cat /home/runner/.npm/_logs/$(date -u +"%Y-%m-%dT%H_%M_%SZ")-debug-0.log
      parallel-commands-on-agents: |
        npx nx affected --target=lint --base=last-release --parallel=3
        npx nx affected --target=test --base=last-release --parallel=3
    secrets:
      NX_CLOUD_ACCESS_TOKEN: ${{ secrets.NX_CLOUD_ACCESS_TOKEN }}
  agents:
    name: Nx Cloud - Agents
    uses: nrwl/ci/.github/workflows/nx-cloud-agents.yml@v0.14.0
    with:
      number-of-agents: 3
    secrets:
      NX_CLOUD_ACCESS_TOKEN: ${{ secrets.NX_CLOUD_ACCESS_TOKEN }}
